version: "3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./heimdall/config:/config
    # ports:
    #   - 5001:443
    restart: unless-stopped
  myst:
    image: mysteriumnetwork/myst:latest
    container_name: myst
    cap_add:
      - NET_ADMIN
    volumes:
      - ./myst/data:/var/lib/mysterium-node
    # ports:
    #   - 5002:4449
    expose:
      - 4449
    restart: unless-stopped
    command: ["service", "--agreed-terms-and-conditions"]
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    env_file:
      - ./mariadb/.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./mariadb/config:/config
    # ports:
    #   - 5003:3306
    restart: unless-stopped
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    env_file:
      - ./nextcloud/.env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    # ports:
    #   - 5004:443
    restart: unless-stopped
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    env_file:
      - ./code-server/.env
    volumes:
      - ./code-server/config:/config
    # ports:
    #   - 5005:8443
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - VALIDATION=http
      - SUBDOMAINS=heimdall,myst,nextcloud,plex #optional
      - CERTPROVIDER=zerossl #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    env_file:
      - ./swag/.env
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
